ifeq ($(CONFIG_OF),y)

dtb-$(CONFIG_SOC_IMX6UL) += \
	mys-imx6ul-14x14-evk-gpmi-weim-lcd070.dtb \
	mys-imx6ul-14x14-evk-gpmi-weim-myb6ulx-lcd070.dtb \
	mys-imx6ul-14x14-evk-gpmi-weim-myb6ulx.dtb \
	mys-imx6ul-14x14-evk-gpmi-weim.dtb \
	mys-imx6ul-14x14-evk.dtb

endif

always		:= $(dtb-y)
clean-files	:= *.dtb
